Nzpmc 002/implement welcome page
UoaWDCC/nzpmc_frontend pull request #7
Opened 2021-05-10 03:46 UTC by ruby-oujo

**Issue**

Updated Homepage with Vuetify components 

**Discussion** 

To do: 
- Video needs to be updated with the NZPMC video 
- "This is a welcome page" will be removed 
- Font to be altered

**Risk**

None 

**Reviewers**

@Will-ZYS  @dtor068

2021-05-10 04:10 UTC, scorpionknifes requested changes
Looks great, just one change!

2021-05-10 04:10 UTC, scorpionknifes commented on src/views/Homepage.vue
> +</style>
Is this file still used?

2021-05-16 01:03 UTC, Will-ZYS approved these changes
LGTM

2021-05-16 01:14 UTC, scorpionknifes approved these changes
LGTM

2021-05-16 01:41 UTC, matthewaptaylor approved these changes
LGTM

2021-05-16 01:41 UTC, merged